### ISSUE TITLE
SavEdit not working

### ISSUE THREAD

**Issue by BoobleJ** [bmgjet/Sav.Edit#10]
Not able to get SavEdit working after the 4/6 update. I'm using the latest Alpha4 version, though it's not properly reading the SAV files.

**Comment by bmgjet** [comment]
Try alpha 5

**Comment by BoobleJ** [comment]
Same issue with Alpha 5. Nothing is populated when opening the new SAV file. Nothing Is populated when importing the old SAV file. The app is still prompting for minimum height as well, which is set to -999 by default.

I am able to open SAV files that were created in past wipes, prior to the 4/6 Facepunch update.

**Comment by bmgjet** [comment]
Can you upload your sav some where. Alpha 5 works with every sav file from my server this year so wondering if maybe its a bad entity in yours.

**Comment by BoobleJ** [comment]
Her is a link containing both original and new SAV files for this wipe.
https://www.dropbox.com/s/pwti26jr6fl8s3v/SAV%20Files.zip?dl=0

**Comment by bmgjet** [comment]
Try Alpha 6, Youll need to use files from your servers managed folder so easiest to just run the exe from there.
I wont be packing them with the exe any more because it will all change next wipe with the netid type change.

Yours it looks like your sav had a wipeid in it even tho it was identified as a older sav type which shouldnt of had that data.

**Comment by BoobleJ** [comment]
Thank you, Alpha 6 is now reading the SAV files. When I click ‘Import data with OwnerID’s’ a box pops up asking for the minimum height, which is set to -999 by default. Not sure what to set here?On Apr 9, 2023, at 11:04 PM, bmgjet ***@***.***> wrote:﻿
Try Alpha 6, Youll need to use files from your servers managed folder so easiest to just run the exe from there.
I wont be packing them with the exe any more because it will all change next wipe with the netid type change.
Yours it looks like your sav had a wipeid in it even tho it was identified as a older sav type which shouldnt of had that data.

**Comment by BoobleJ** [comment]
Should I leave at the default -999 when prompted?On Apr 10, 2023, at 10:18 AM, ryan hanley ***@***.***> wrote:﻿Thank you, Alpha 6 is now reading the SAV files. When I click ‘Import data with OwnerID’s’ a box pops up asking for the minimum height, which is set to -999 by default. Not sure what to set here?On Apr 9, 2023, at 11:04 PM, bmgjet ***@***.***> wrote:﻿
Try Alpha 6, Youll need to use files from your servers managed folder so easiest to just run the exe from there.
I wont be packing them with the exe any more because it will all change next wipe with the netid type change.
Yours it looks like your sav had a wipeid in it even tho it was identified as a older sav type which shouldnt of had that data.
