### ISSUE TITLE
Not working version 7

### ISSUE THREAD

**Issue by jakub96124124** [bmgjet/Sav.Edit#11]
Hello, doesn't work can't open even in version 7.
I am also sending files to test. Thank you 

https://drive.google.com/file/d/12o_M-trGW9KGdzjDdoHW6J5aHOZyagBQ/view?usp=share_link

**Comment by bmgjet** [comment]
Needs to be run from a servers install managed folder since it needs the files from that.
Such as
"C:\Rust\RustDedicated_Data\Managed"
